### ISSUE TITLE
find a domain name that would fit sanctuary

### ISSUE THREAD

**Issue by ebb-tide** [S5S-Sanctuary/Sanctuary_Prototype#3]
I'm going to set up a dedicated digital ocean instance (server) for this, would be nice if we had a snazzy domain name that was easy to use. s5ssanctuary has too many s'es, s5sanctuary? 
maybe you could look on godaddy or google domains for a cheap (20$ a year ish?) domain name that is available? if you want. I can do it too later

**Comment by sofiajeanne** [comment]
we could get sanctuaries.me for $20/year. that's the snazziest option, it's kind of nice without the ambiguity of s5.

**Comment by sofiajeanne** [comment]
sanctuaries.co ftw!
